version: '3.8'

services:
  db:
    image: postgres:17-alpine  
    container_name: postgres_dev
    restart: always
    environment:
      POSTGRES_USER: kubo_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kubodb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql  

  backend:
    image: python:3.11-slim
    container_name: kubo_backend
    restart: always
    working_dir: /app/backend
    environment:
      DATABASE_URL: postgresql://kubo_user:password@db:5432/kubodb
    depends_on:
      - db
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    command: >
      sh -c "pip install --no-cache-dir fastapi 'uvicorn[standard]' psycopg2-binary pydantic pydantic-settings python-dotenv email-validator 'passlib[bcrypt]' 
      && uvicorn main:app --reload --host 0.0.0.0 --port 8000"

volumes:
  postgres_data:
