version: '3.8'

services:
  db:
    image: postgres:17-alpine  
    container_name: postgres_dev
    restart: always
    environment:
      POSTGRES_USER: kubo_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kubodb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql  

volumes:
  postgres_data:
